### ISSUE TITLE
[Question] Difference between this and Client?

### ISSUE THREAD

**Issue by Shuyinsama** [Prophetly/prophetly-server#3]
Just wanted to say awesome work and a good use of the library!

I have cloned both the server and the client but I fail to see the major differences.
I understand that the Client requires the server to be running but I can make the same calculations on the server?

Or is the react client made with Electron in mind? to server as a desktop application?

As a side question: I think this is a really interesting project and would love to see this getting more support. Currently it requires the upload of a CSV file to assign the columns and do the calculations.
But would it be possible to directly serve arrays into prophet? Maybe through an API endpoint? 

For example: At my company we have a custom in-house made analytics tool which connects and grabs data through multiple sources. While currently not available I could of course create a `export to csv` button and and generate the correct output. But it kind of a break in the workflow of the app. It would be nice to be able to click on for example `Forecast data` and it would send the correct data to prophet which in it's turn does the prediction and sends it back?

Awesome work and many thanks!

**Comment by pravj** [comment]
Hi @Shuyinsama,

First off, extremely sorry that I didn't reply to your question.
Would like to initiate the conversation again if you don't mind.

I went with the client-server approach because I wanted to learn React.
Agree that an API based design will be more scalable across different type of clients, didn't think (when I was implementing) that it will be useful to someone.

There are a few ideas to improve the project:
* Docker-based setup to minimize the configuration problems
* API layer to support custom clients

I won't be able to give you possible timelines as I don't get personal time nowadays. But I will try to create issues and public roadmap in case someone is willing to contribute.

Happy to hear that you've found it helpful. 🎉 

Again, sorry for missing the original discussion.
